/* This file is automatically generated by Lux. Do not modify. */

import * as Model from '@/XIV/Models/Generated';

export type EventStreamType = {
    'VisibleNativeElements': string[];
    'PlayerActor': Model.PlayerActor;
    'PlayerActors': Model.PlayerActor[];
    'NpcActors': Model.NpcActor[];
    'GatheringNodeActors': Model.GatheringNodeActor[];
    'Camera': any;
    'GameState': Model.GameState;
    'HousingMarkers': Model.HousingMarker[];
    'QuestMarkers': Model.QuestMarker[];
    'CurrentWeatherForecast': Model.WeatherForecast[];
    'CurrentZone': Model.Zone;
    'SelectedZone': Model.Zone;
    'FlagMarker': Model.FlagMarker;
    'Waymarks': Model.WaymarkMarker[];
    'Fates': Model.FateMarker[];
}
